### ISSUE TITLE
Nuggets

### ISSUE THREAD

**Issue by Lordician** [Sinhika/SimpleOres2#11]
I am currently playing with this mod together with some other mod that changes the smelting to only give a nugget, however, simple ores sadly does not have nuggets of it's metals.
So i would like to suggest to add nuggets of your metals for just this extra bit of mod compatibility.

**Comment by Sinhika** [comment]
This is a good idea. I could add it to the 1.11.2 version, or wait until the port to 1.12. Any preference?

**Comment by Lordician** [comment]
Personally i am playing on 1.11.2 (mainly due to some mods that have not been updated to 1.12 yet, for example ice and fire).
So i would prefer 1.11.2, but if you wait until the port to 1.12 i can understand.

**Comment by Lordician** [comment]
Sorry for posting it in both things, but i figured i might as well since it might help you in managing what you have/want to do still.
While i am at it, fusion's metals do not necessarily need nuggets since they are alloys, but while you are at it, maybe add it, just in case.

**Comment by Sinhika** [comment]
Nuggets are being added in 1.14+ versions.
