### ISSUE TITLE
Cannot use bows from the mod

### ISSUE THREAD

**Issue by SpringsTS** [Sinhika/SimpleOres2#12]
Hi,

I registered on GitHub to be able to post this issue: I cannot use the bows from the mods in Survival mode. Happens for Mythril, Onyx (and Sinisite with the Fusion mod).
_ When I'm in Creative mode, no problem
_ When I'm in Survival, while I keep the right button down, the bow is animated like if I change of tool in my hand.

Tested with Minecraft 1.11.2 + Forge 13.20.1.2513 + the last version of the mods.
Also tested with only CompatLayer, SimpleCore and Simple Ores on a fresh new world, same problem.

Thanks in advance!

**Comment by Sinhika** [comment]
Well, I have duplicated the problem, at least. I will be looking into it soon.

**Comment by Sinhika** [comment]
Fixed with latest release of **SimpleCore API,** https://minecraft.curseforge.com/projects/simplecore-api/files/2494558

**Comment by SpringsTS** [comment]
Thank you, you're the best!
