### ISSUE TITLE
[1.12.2] Tipped and other special Arrows do not deplete when fired from a SimpleOres2 bow with an Infinity enchantment.

### ISSUE THREAD

**Issue by fandomaniac** [Sinhika/SimpleOres2#13]
When firing Vanilla Tipped Arrows (Harming, Healing, Swiftness, etc.) or modded arrows (Extra Arrows from Quark), from a Mythril or Onyx Bow with an Infinity Enchantment, this does not deplete the arrow as it would with a vanilla bow with Infinity.

**Comment by fandomaniac** [comment]
This bug still exist in the latest version: 1.12.2-1.11.2.0.

**Comment by Sinhika** [comment]
Yep, it's a bug. Obsolete code that was cut & pasted & edited from the vanilla ItemBow code before tipped arrows were a thing.

**Comment by Sinhika** [comment]
Fixed by simplecore-1.12.2-1.7.3.4 and SimpleOres2 1.12.2-1.11.2.2
