### ISSUE TITLE
Bows Cannot Be Repaired on Anvils

### ISSUE THREAD

**Issue by fandomaniac** [Sinhika/SimpleOres2#17]
Bows cannot to be repaired on anvils. I've tried Onyx and Mythril Bows with no success. However, I seem to be able to repair swords and other tools with no issues.

![image 1](https://user-images.githubusercontent.com/37810246/47599038-dd2d4c80-d973-11e8-9f5f-f4e60a3a28dd.jpg)

**Comment by Sinhika** [comment]
I looked into this.

1. Normal repair material for the bows are mithril and onyx _rods_, for mythril and onyx bows respectively. Note that a vanilla bow cannot be repaired with raw ingredients on an anvil at all.
2. Vanilla bow repair mode on an anvil (damaged bow + bow) also works with Simple Ores bows, though material-wise you're far better off using the rods for repair materials.

In both cases, you retain the enchantments on the leftmost bow when it is repaired.

**Comment by fandomaniac** [comment]
Sorry Sinhika, the document I read online that mentioned ingots for repair must have been outdated.

**Comment by Sinhika** [comment]
You are right about that... The SimpleOres Wiki is a bit out-of-date, but, to my surprise, it looks like I have edit priviledges there, so I will update it. I did not think I had edit privs there (it's AleXndr's old wiki)
