### ISSUE TITLE
Duplication bug with Simple Bows

### ISSUE THREAD

**Issue by fandomaniac** [Sinhika/SimpleOres2#18]
If you fire a tipped arrow from a Simple Ores bow and are able to retrieve the shot arrow, you will get that arrow back plus have an additional arrow added to your inventory. I tested with a Mythril Bow with Mending and fired a Spectral arrow,

![2018-11-06_10 13 26](https://user-images.githubusercontent.com/37810246/48073816-8adaff80-e1ad-11e8-8a10-05f0514c1cdc.png)
![2018-11-06_10 13 31](https://user-images.githubusercontent.com/37810246/48073818-8adaff80-e1ad-11e8-877c-6a856da42f0a.png)
![2018-11-06_10 14 28](https://user-images.githubusercontent.com/37810246/48073820-8adaff80-e1ad-11e8-899c-8b14906f1f87.png)
![2018-11-06_10 19 17](https://user-images.githubusercontent.com/37810246/48073821-8b739600-e1ad-11e8-8ec2-ad002009b8dc.png)

**Comment by fandomaniac** [comment]
You can keep firing them at the ground and every time you retrieve the arrow you increase your arrow count. This was also done with a bow without the Infinity enchantment.

**Comment by Sinhika** [comment]
1.12.2 is no longer in maintenance; problem hopefully fixed in 1.14.3.
