### ISSUE TITLE
Unable to get ore to spawn in other dimensions.

### ISSUE THREAD

**Issue by gkuba** [Sinhika/SimpleOres2#2]
Hello,

I am currently trying to get the ores from this pack to gen in other dimensions such as the Aroma 1997 mining dimension which uses overworld type generation. Is there a config setting or something I can set to force it to spawn in other dimensions as well?

Thanks

PS I'm using the latest 1.10.2 download from curse and have the core as well as fusion and netherrocks.

**Comment by Sinhika** [comment]
You currently can't do that. I haven't added custom dimension ore generation back in yet... the old system was a bit confusing.

**Comment by gkuba** [comment]
Ok thanks, I will have to look into an alternative way to force gen or retro gen them until then.

**Comment by Sinhika** [comment]
Anyone know if this is working in 1.14.3? I don't have an alternate overworld dimension mod around to test with.

**Comment by Sinhika** [comment]
Ore generation was completely re-written as of 1.15.2.
