### ISSUE TITLE
[1.12.2] Holding right click while switching bows in the hotbar crashes the game

### ISSUE THREAD

**Issue by cutcat101** [Sinhika/SimpleOres2#27]
Crashes every time when switching from a simpleores bow to a non simpleores bow

Switching from a vanilla bow to a simpleores onyx bow:
https://paste.dimdev.org/eteqijamop.mccrash

Switching from a betterwithmods compound bow to a simpleores mythril bow:
https://paste.dimdev.org/umemaxajey.mccrash

Other crashes:
https://paste.dimdev.org/motuquhivu.mccrash
https://paste.dimdev.org/degexuqoga.mccrash

Thanks!

**Comment by kil0byt3** [comment]
Also apparently food: 
"If you rapidly switch between food and a mythril bow while charging the bow, it causes you to crash"

https://paste.dimdev.org/duwejeliju.mccrash

**Comment by Sinhika** [comment]
I am no longer maintaining the 1.12.2 versions.
