### ISSUE TITLE
How to change config files on a forge server?

### ISSUE THREAD

**Issue by glowstoneturtle** [Sinhika/SimpleOres2#29]
Hi there, 
I host my own modded server on Forge. I heard this mod was completely editable to your preferences. I want to make mythril and adamantium less OP. I'm trying to find the config files on my server, but I can't find them anywhere. Is it possible to change these values and where do I do this in the files to apply it to my server?

**Comment by Sinhika** [comment]
Which Minecraft version?

**Comment by glowstoneturtle** [comment]
1.14.4

**Comment by Sinhika** [comment]
The original 1.14.4 port did not have anything configurable except turning the ores on and off. The current 1.15.2 version has configurable ore generation, but not armor/tool parameters, yet.

**Comment by glowstoneturtle** [comment]
Gotcha, thank you!
