### ISSUE TITLE
1.10.2 Armor Reduction array reversed 

### ISSUE THREAD

**Issue by TheOldOne822** [Sinhika/SimpleOres2#3]
At some point between 1.7.10 and 1.10.2 Minecraft reversed the order of the armor damage reduction array I don't know when it happened and it could have been form 1.9 to 1.10 but in 1.10.2 it is [boots, legs, chest, helm] and SimpleOres family of mods are sending it [Helm, Chest, Legs, Boots].
I was going to post it to Simple Core because it effects all 3 but after looking at the code I see it's not actually a problem in Simple Core.
As a result all armors in Simple Ores, Fusion, and Netherrocks have the reduction values wrong, the Helm and Boots are switched as are the Chest and Legs.
Copied to all 3 mods.

**Comment by Sinhika** [comment]
...found the problem, it's where I initialize ArmorMaterial for each custom material. It would have been helpful to let me know that's where the issue was, because I wasted a fair bit of time staring at the config file code, which was fine. ;-)  Next version I push out should have the fix.

**Comment by Sinhika** [comment]
Fixed with Simple Ores 2 1.9.1.3.
