### ISSUE TITLE
Compatibility with Industrial Reborn for 1.16.1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Sinhika/SimpleOres2#36]
Add compatibility for [Industrial Reborn](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn) so [SimpleOres](https://www.curseforge.com/minecraft/mc-mods/simpleores) can be used to be used for crafting of their machines and cables.

**Comment by Sinhika** [comment]
**Industrial Reborn** is a closed-source mod. My metal ingots already have forge tags so they can be used in recipes that call for "forge:ingots/copper" or "forge:ingots/tin". Without some kind of public API or documentation for **Industrial Reborn**, there is nothing further that I can do.

**Comment by ClaudiusMinimus** [comment]
Thank you!
