### ISSUE TITLE
Tin/Copper Blocks not crafting to ingots

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Sinhika/SimpleOres2#37]
While JEI shows you can craft block to ingot for both copper and tin if you put a block in a crafting table there is no output.

SimpleOres2 1.16.1-2.2.0.0

**Comment by Sinhika** [comment]
I am unable to duplicate this bug; it works fine when I test it with Forge 32.0.59, SimpleOres2 1.16.1-2.2.0.0, and JEI. Perhaps you have some additional mods that are causing a recipe conflict or altering recipes?
