### ISSUE TITLE
Ores can be mined by hand

### ISSUE THREAD

**Issue by medsal15** [Sinhika/SimpleOres2#40]
Tin, copper, onyx, adamantium, and mythril ores can be mined without a tool in survival

**Comment by Sinhika** [comment]
Which version of Minecraft & Simple Ores has this problem?

**Comment by medsal15** [comment]
Minecraft 1.16.1, Simple Ores 2.2.0.1, Forge 32.0.106

**Comment by Sinhika** [comment]
Ah, I thought that might be it. Fixed with Simple Ores 2.2.0.2.
