### ISSUE TITLE
Metal Dusts for 1.16.x?

### ISSUE THREAD

**Issue by Wiccat** [Sinhika/SimpleOres2#41]
Would it be possible to add dust objects for SimpleOres2 in the next update for 1.16.x?
Would make integrating SO into other mods easier.

**Comment by Sinhika** [comment]
Once I finish porting the various add-on mods at 1.15.2 or 1.16.1 to 1.16.3, I'll poke at dusts.  I'm almost done with the 1.16.3 ports, so that will be soon.

**Comment by Sinhika** [comment]
I've been aiming primarily at Silent's Mechanisms, which already provides copper and tin dusts. I have only implemented mythril dust and adamantium dust so far. Does Simple Ores need to provide its own copper and tin dust?

**Comment by Wiccat** [comment]
For compatibility with other tech mods, it probably wouldn't hurt. That said, I've been using SimpleOres2 + JAOPCA under 1.15.2/1.16.1 and the only issue has been with mythril and adamantium not having any dust elements in any of the addons, and so crushing nuggets for these - just destroys the nuggets and leaves air.

**Comment by Sinhika** [comment]
Okay, there are now dust and crushed ore objects for all SimpleOres2 ores & metals except onyx. My theory for onyx is that it is too brittle for crushing and shatters into useless gravel if fed to a crusher/grinder.
