### ISSUE TITLE
Copper gear (Copper Tools, Sword, and Armor) Noncraftable/Uncraftable/Unobtainable In Survival Mode

### ISSUE THREAD

**Issue by Coraline77447** [Sinhika/SimpleOres2#44]
Hi, I've noticed that before my world that I played on was un-joinable due to errors in selected datapacks that I was not able/unable  to craft copper armor and tools so I've disabled copper's ore generation and items for now till the issue is fixed unless the latest update fixes this issue then you can simply ignore this. Also I have JEI installed and when I was trying to see Copper's recipes I wasn't able to see any recipes for anything made out of Copper either, which also means that I've temporarily disabled Copper's crafting recipes for now till this issue is fixed

**Comment by Sinhika** [comment]
Which version of Minecraft, Forge, and SimpleOres are you using? If later than MC 1.15.2, what version of SimpleCoreLib are you using?

**Comment by Coraline77447** [comment]
I'm using Minecraft 1.16.4, Forge 1.16.4 now at 35.1.0 for Forge, and at the moment Idk what version of SimpleCoreLib I'm currently using but it should be the least version, when I'd reported this issue I was using Forge version 35.0.7 or 35.0.17 I think (before the wierd crash thing started to happen when I'd jinksed myself by accident so I was basically forced to update to 35.0.18 which fixes the wierd crash). Before I start my next modded minecraft play session I'll be looking for updates to the mods that I'm playing with and when I'm installing the new updates to mods that have been updated I'll check what version SimpleCoreLib is. I know, you need the info as soon as possible or even right now so that you could tell me what's causing this issue and all and you'll get the information as soon as I possibly can but as of right now that's not possible cause ima be doing other things first. Ok? I promise I'll provide you with the information that you need in order to get this issue resolved as long as I don't accidentally forget about it and I'm also sorry for no reply for the past few days...

("Before I start my next modded minecraft play session I'll be looking for updates to the mods that I'm playing with and when I'm installing the new updates to mods that have been updated I'll check what version SimpleCoreLib is. I know, you need the info as soon as possible or even right now so that you could tell me what's causing this issue and all and you'll get the information as soon as I possibly can but as of right now that's not possible cause ima be doing other things first. Ok? I promise I'll provide you with the information that you need in order to get this issue resolved as long as I don't accidentally forget about it"  Actually I'll go check what version of SimpleCoreLib that I'm using before I go watch some YouTube videos from my favorite youtubers since I'm just going to look at what version of SimpleCoreLib that im currently using which shouldn't take too much of my time anyways)

UPDATE: Here's the version of SimpleCoreLib that I'm currently using: 2.0.2.0
Also I know that what I'm going to say isn't important or anything but why I'm not using Zot's Only Silver and Sterling and Black is so that I don't have too many varieties of tools, weapons, and armor but I am using Fusion tho cause Fusion has some nice shade of blue tools, weapon, and armor which to me looks like navy blue or royal blue and that its the best in my modded game (Sinisite I think that it's called) but I wish that the textures of everything in Fusion were up to date but the current textures for everything in Fusion are fine the way they are

**Comment by xd4rkzghost01** [comment]
Got The Same issue here and this is a lil' bit lame, cause it seems copper overtake on iron in the spawnrate so this is now my common ores in the overworld and we can't make gear from it.

MC : 1.16.4
Forge : 35.0.15
All the mods i use 
![mods1164](https://user-images.githubusercontent.com/63568312/99899285-0402fd80-2c76-11eb-9875-ab93fe50d55e.png)

The Latest .log files
[latest.log](https://github.com/Sinhika/SimpleOres2/files/5579179/latest.log)

Hope this can help.

**Comment by Sinhika** [comment]
I tested with SimpleOres2-1.164-2.4.2.1 and SimpleCoreLib-1.16.4-2.0.2.0, JEI 1.16.3-7.3.2.36, and Forge 35.1.0, with no other mods. I was unable to duplicate the error; I was able to create copper tools in the crafting table in both Creative and Survival mode. 

@xd4rkzghost01  your error logs show that the forge:ingots/copper tag is not defined. SimpleOres 1.16.4-2.4.2.1 definitely defines that tag; is it possible some other mod is deleting forge tags? 
@Coraline77447 What version of SimpleOres are you using, and are you using any other mods along with it? Do you have any log files?

**Comment by xd4rkzghost01** [comment]
As you say i've try to find "a" mod or some mods that may cause the problem and i dint find it . BUT i try at least to set to False the Copper Generation and it dint works... i still get copper now even if i disable all the copper tool/ores ect. in the mod config.files

**Comment by Coraline77447** [comment]
I'm using the latest version of SimpleOres2

2.4.2.1

Btw Fusion has incompatible datapack(s) when I looked onto the data pack option when I was making a new world after my last one was un-joinable due to selected datapacks that have errors (incompatible, made for an older version of Minecraft). I don't know why me and any other people cant craft Copper tools, weapon (sword) and the armor but I don't have Simple Ores installed currently cause I'm playing with a gun mod called A.V.A now (which also has incompatible datapack) till I cant rejoin my current modded world anymore due to the selected datapacks of A.V.A, Artifacts (I've recently downloaded and installed an update for Artifacts mod), and FTB Ultimate (which is ALOT like Vain Miner but with white outlines while Vain Miner doesn't have that) that had incompatible datapacks . Which is why I don't have Simple Ores installed is cause I would've had too many weapons and to choose to use swords, bows, and crossbows or use guns from a.v.a mod

**Comment by Sinhika** [comment]
@xd4rkzghost01 this may be a silly question, but are you creating a new world when you check for copper generation? Old copper veins won't disappear just because you turned off new copper ore generation.

Trying to find the conflicting mod can be tedious; start with just SimpleCoreLib & SimpleOres in a test world, and see if you can duplicate the copper tool problem. If not, add mods one at a time and test until you see the problem again. The mod you added last is the one messing things up. Also, don't overlook CraftTweaker scripts as possible trouble sources.

If there's a mod out there deleting the forge ingot tags for copper, it's going to cause problems for a lot more mods than mine, as copper is a very popular ore for tech mods.

A belated thought: you didn't get your mods from some other source besides CurseForge or the author's own site, did you? Certain sites, such as 9minecraft, are shady and re-post mods without asking and claim they are for later Minecraft versions than they actually are. You don't know what you are getting from such sites.

**Comment by Coraline77447** [comment]
Ik that your latest reply to xd4rkzghost01 may not be what's happening to me with the Copper stuff but I've recently (like just now) been thinking that what if it's one of the mods that I'm playing with that is conflicting with Simple Ores's Copper but I seriously don't know which mod that I was playing with that was causing this confliction with Simple Ores and I dont think that any of the mods that I have adds Copper and even if one of them does it shouldn't conflict cause of the item IDs for copper and with JEI and a recipe conflicting prevention mod that prevents the recipes from conflicting with each other but allow them to work with each other respectfully to allow us to craft Copper armor and stuff in their respective mods and even allow other mods Copper to be used in another mods recipe to craft either mods Copper stuff but idk if the one recipe confliction prevention mod for 1.16 has been updated to 1.16.4 yet or else I would've been using that mod so that all recipes wouldn't be conflicting with one another.

To be completely honest I truly don't know exactly why I'm not able to craft Copper armor and tools (and sword) when the items are clearly in the game which means they're in the mod but its like their recipes aren't in the mod in order to craft them, if the recipes for those items are in the mod then why cant JEI see those recipes in the first place? 

For what's been happening with xd4rkzghost01, that issue seriously needs to be resolved or else that issue will be really bad for the modding community as a whole and alot of people and the owners of tech mods and mods that adds Copper to the game are gonna be furious till the issue can be tracked back to which ever mod is causing that issue and immediately report the issue to the owner of whatever mod is causing this and to tell the owner to immediately fix that issue. Btw I hope that I wasn't experiencing that issue when I was playing with Simple Ores while I was experiencing with the issue that's been plegging me as of not being able to craft Copper armor, tools, and sword.

**Comment by xd4rkzghost01** [comment]
(1st thing off : i'm trying to understand and write my possible in english but i'ma native language is french so i'm sorry if i made some miss-spelling)

God i hate you :D I just finished checking 1 by 1 every mod i have installed and FINALLY, 2 day later; after drag in-n-out 61 mod;  i find the 1 causing the error

MoreVanillaWeapons:
https://www.curseforge.com/minecraft/mc-mods/morevanillaweapons

Dunno really how coding and java works in minecraft but i forgot to search longer and he seem to have a Library for his mods that i dint dowload last time. And even if i download the Lib for MVW, your mod and his arent compatible, Copper tools and armor are uncraftable from each of one mods.
@Sinhika For the Mods that i download. They came all from Curseforge, i dont trust 9craft or other websites.
@Coraline77447  Seems like i dont have the "same" exact problem :(  I'm sorry that dint help

**Comment by Sinhika** [comment]
The problem is in MoreVanillaWeapons, and I will attempt to bring it to the dev's attention.

**Comment by Coraline77447** [comment]
I know that you closed this issue but....

![20201127_030245](https://user-images.githubusercontent.com/72243304/100436871-2ffaf600-305d-11eb-9f64-59e08eb44709.jpg)

I'm in creative mode and thought that my issue has been fixed but apparently not yet and we still dont know what's causing this to happen and yes I currently have MoreVanillaWeapons installed and it's the latest version of; SimpleCoreLib, SimpleOres2, and MoreVanillaWeapons... WAIT A SECOND! I'd just remembered that I tried to disable Copper stuff and its ore generation cause there was an issue with copper as if the confliction between this mod and MoreVanillaWeapons, so ima go to SimpleOres2's config and turn all of Copper's stuff back on and see if that fixed what I'm seeing right now.

EDIT: Nope... Still unable to craft the copper sword...

**Comment by Sinhika** [comment]
It's a problem with MoreVanillaWeapons--the dev incorrectly implemented forge tags, and as a result, wipes out EVERYONE's forge tags of the same type (e.g. "forge:ingots/copper") AND the recipes that depend on those tags. I've reported the issue to the dev in his CurseForge project comments; I can't fix it for him for various legal and physical reasons. It's not a bug in SimpleCoreLib or SimpleOres, so I closed the issue after reporting it to the person and mod the bug does belong to.

Right now, the workaround is either (1) don't use MoreVanillaWeapons, or (2) use MoreVanillaWeapons, but don't use any other mod that provides the same materials as MVW.

**Comment by Sinhika** [comment]
MoreVanillaWeapons 1.16.2/3/4-1.4.2 fixed the problem at their end; it appears to work okay with SimpleOres now.

**Comment by Coraline77447** [comment]
Yeah, it's working now. I'd literally just crafted and enchanted both the Copper gear from your mod and crafted MVW's Copper weapons yesterday  morning since they've added support for SimpleOres2's Copper to be used for crafting their weapons so now MVW doesn't only support Ice&Fire mod for copper except for silver that only Ice&Fire supports with still which I'll still be waiting for them to add more support from other mods that adds silver to the game. Btw for what you've said "Right now, the workaround is either (1) don't use MoreVanillaWeapons, or (2) use MoreVanillaWeapons, but don't use any other mod that provides the same materials as MVW." The only mods that's adds copper is yours since CLib (a library mod for CArmory and it adds ores and it's own version of copper) has some issues right now and both the owner of CLib and I don't know what's causing the problem with CLib, also I bet that both CLib and CArmory have outdated datapacks and probably cant manually update their pack_format meta version, so even if the problem that CLib is experiencing I still wouldn't be able to play with CLib probably cause of its outdated datapack and CArmory's as well. Also I've had my own workaround with this resolved problem when it was still a problem which I just didn't use the copper gear and wasn't able to craft MVW's copper weapons anyways but if I were to find copper items say like a copper sword I would use it cause why not? It would've been a waste even tho I wasn't able to craft a copper sword at the time but if I'd never found any copper items in loot chests like say in a village weaponsmith chest then I  wouldn't use it cause I wouldn't have found it. I've just been thinking about a suggestion within this closed issue report that in the config file where it puts SimpleOres2's items into cheats, maybe make that more configurable so that if someone didn't want to find say a onyx axe in a desert temple (that's where I commonly find onyx items is in desert temples) or if there would be a problem similar to this one then we would be able to disable loot chests to have certain material items like for an example copper items so that we can still play with SimpleOres2 and whatever mod that adds their own version of the material that SimpleOres2 adds without being able to use those items since a different mod would have caused a problem with SimpleOres2.
