### ISSUE TITLE
Disabling oregen via config does not work

### ISSUE THREAD

**Issue by Calendis** [Sinhika/SimpleOres2#47]
The OreGeneration section, with the EnableCopperOre, EnableTinOre, etc. settings, does not work. I have set each to false and it still generates the respective ores.

Notably, the mod DOES obey the other ore generation settings, such as vein size, etc. Right now my workaround to "disable" an ore is to set its max height lower than its min height, but this seems like an ugly hack.

Info:
Minecraft:         `1.16.4`
Forge:               `35.1.5`
SimpleOres:      `2-1.16.4-2.4.3.8`
SimpleCoreLib: `1.16.4-2.0.4.3`

**Comment by Sinhika** [comment]
Oh, oops. My bad. When I rewrote the ore generation code to work correctly under 1.16.4, I completely forgot to check the ore generation config flags before registering & generating ore. I'll address that early this coming week sometime.

**Comment by Sinhika** [comment]
Forgot to close this. Fixed as of 1.16.4-2.4.3.9.
