### ISSUE TITLE
Wrong Forge Version??

### ISSUE THREAD

**Issue by EverlastingYT** [Sinhika/SimpleOres2#49]
Hello! I am having an issue loading this mod up with Curseforge. I have tried starting it up but I am met with this everytime.
![image](https://user-images.githubusercontent.com/45980432/115065533-3c70d580-9ebc-11eb-9b2f-8b0629592c01.png)
The Minecraft version I am trying to load it on is 1.14.4 and there is no forge version on curseforge that corresponds to the mod's requirements.

**Comment by EverlastingYT** [comment]
Also, this is the latest 1.14.4 forge version there is on curseforge.
![image](https://user-images.githubusercontent.com/45980432/115065872-b99c4a80-9ebc-11eb-98a9-e9840cdc98a9.png)

**Comment by EverlastingYT** [comment]
Although, it is listed on the forge website itself.
![image](https://user-images.githubusercontent.com/45980432/115068936-ec484200-9ec0-11eb-9dbb-614f220c2525.png)

**Comment by EverlastingYT** [comment]
But I do not know how to import that forge version into curseforge; or if it is even possible to do so.

**Comment by Sinhika** [comment]
It requires 28.2.4 **_or above_**.  Just get a later version. It requires features added in 28.2.4, so later versions work.
