### ISSUE TITLE
[1.17] all mod achievements auto complete when I start a new world

### ISSUE THREAD

**Issue by ffuentesm** [Sinhika/SimpleOres2#51]
In the latest version of the mod (SimpleOres2-1.16.5-2.4.7.2.jar) when I start a new world all the achievements get auto-completed.
 
![image](https://user-images.githubusercontent.com/44974827/132161609-5c0ec664-2649-4983-8496-1853a0c5f627.png)

**Comment by Sinhika** [comment]
Creative mode or Survival mode?

**Comment by ffuentesm** [comment]
> Creative mode or Survival mode?

I am in survival.

**Comment by Sinhika** [comment]
Okay, I found the problem. I should get it fixed this weekend at the latest. Assuming another hurricane doesn't swing by.

**Comment by Sinhika** [comment]
Fixed with release 1.17.1-3.0.1.3.

**Comment by aleclux** [comment]
Hi!
In the release 1.17.1-3.0.1.4 it happened again. <3
