### ISSUE TITLE
Can't craft any item of the mod that uses minecraft:copper_ingot

### ISSUE THREAD

**Issue by W1Real** [Sinhika/SimpleOres2#53]
- Minecraft 1.18.1
- Forge 39.0.10
- SimpleCoreLib 4.0.0.2
- Simple Ores 4.0.0.0

Tested on a fresh install, no conflict with other mods. `/give` works just fine.

**Thank you so much! Great mod!**

**Comment by Sinhika** [comment]
Try updating your version of Forge to the latest. The early versions, like 39.0.10, didn't have copper correctly tagged. I have not been able to duplicate your bug using Forge 39.0.59.
