### ISSUE TITLE
mithril_ore does not smelt in furnace

### ISSUE THREAD

**Issue by Gaxon1** [Sinhika/SimpleOres2#54]
simpleores:mithril_ore does not smelt in any furnaces.

Forge 39.0.66
SimpleOres2-1.18.1-4.0.0.1

**Comment by Sinhika** [comment]
Nice catch; I forgot to retain mythril ore furnace recipes when I converted the old recipes to raw_mythril. Will push fix in the morning.

**Comment by Sinhika** [comment]
Fixed in release 1.18.1-4.0.0.2
