### ISSUE TITLE
BUG: Copper bucket doesn't collect water

### ISSUE THREAD

**Issue by Gaxon1** [Sinhika/SimpleOres2#56]
Copper bucket doesn't collect water on right click.
Forge 39.0.76
SimpleOres2-1.18.1-4.0.0.2

**Comment by Sinhika** [comment]
Unable to duplicate with Forge 39.1.2, SimpleCoreLib 1.18.1-4.0.1.0 and SimpleOres2 1.18.1-4.0.0.5.
Closed until I get further information allowing me to duplicate this bug report.
