### ISSUE TITLE
Simpleores Has Failed to Load Correctly: java.lang.NoClassDefFoundError: mod/alexndr/simplecorelib/config/ISimpleConfig

### ISSUE THREAD

**Issue by Coraline77447** [Sinhika/SimpleOres2#60]
Minecraft: 1.18.2
Forge: 40.1.0
SimpleOres: 1.18.2, 4.1.0.5
SimpleCoreLib: 1.18.2, 4.3.0.3

https://pastebin.com/SyHQC8vE

**Comment by Sinhika** [comment]
Use SimpleOres 1.18.2-4.1.1.0 with SimpleCoreLib 1.18.2-4.3.0.1 or later. SimpleCoreLib 4.3.0.1 was a major refactoring. I will be archiving the older versions so people don't accidentally load them like you did.
