### ISSUE TITLE
1.20.1 - 6.0.0.3 | Crashes when used with rubidium

### ISSUE THREAD

**Issue by soupbowle** [Sinhika/SimpleOres2#66]
I was trying to play with the rubidium mod and it crashes when I render a copper lava cube. You can see it just typing lava in the creative tab.

Here is the crash log: https://pastebin.com/abcp8r78

I hope it will be useful.

**Comment by Sinhika** [comment]
You may need to file this with the BucketLib project, as the copper_bucket uses BucketLib. BucketLib uses a few mixins, those may be in conflict with Rubidium's mixins.
