### ISSUE TITLE
Smelting copper gives no EXP in 1.10.2 1.9.1.3

### ISSUE THREAD

**Issue by Dubster94** [Sinhika/SimpleOres2#9]
Hello! Title should really say it all. In the meantime, I've created a MineTweaker script that fixes this bug, so this issue is not exactly critical.

**Comment by Sinhika** [comment]
XP rate for copper is too low, but it is there. Slow XP rate means that only every Nth copper bar shows an XP jump when you take it out. XP rate needs to be boosted to something like iron's.
